server:
  port: 8080
  tomcat:
    connection-timeout: 10000
##服务监控
management:
  endpoints:
    web:
      exposure:
        include: 'loggers,health,prometheus'

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev


playwright:
  pool:
    pool-size: 100                   # 连接池大小
    timeout-seconds: 5               # 获取超时时间
    headless: false
    ignore-https-errors: true
    browser-type: chromium
    viewport-width: null
    viewport-height: null
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"

