server:
  port: 8080
  tomcat:
    connection-timeout: 10000
program:
  name: sztu
  code: 10001

##服务监控
management:
  endpoints:
    web:
      exposure:
        include: 'loggers,health,prometheus'
middleware:
  redis: "192.168.3.35"
#  rocketmq: "192.168.18.79"
#  kafka: "192.168.1.132"
#  nacos: "192.168.18.79"
#  edge: "192.168.1.63"

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  data:
    ##redis
    redis:
      host: ${middleware.redis}
      port: 6379
      password: ${passwd.redis}
      database: 0


school:
  url:
    gateway: https://home.sztu.edu.cn/bmportal
    login: https://auth-sztu-edu-cn-s.webvpn.sztu.edu.cn:8118/idp/authcenter/ActionAuthChain
    sms-send: https://auth-sztu-edu-cn-s.webvpn.sztu.edu.cn:8118/idp/sendSMSCheckCode.do

playwright:
  pool:
    pool-size: 100                         # 连接池大小
    timeout-reqest-duration: 5000000       # 单个playright请求超时时间
    timeout-poll-seconds: 5                # 获取超时时间
    headless: false
    ignore-https-errors: true
    browser-type: chromium
    viewport-width: null
    viewport-height: null
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36

sztu:
  constant:
    projectOrBrandName: ${program.name}
    projectOrBrandCode: ${program.code}
    projectName: ${program.name}
    environment: ${spring.profiles.active}
